//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaorCore.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaorCore.I18N.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive trace control with upper and lower thresholds.
        /// </summary>
        internal static string adaptive_trace_control_descr {
            get {
                return ResourceManager.GetString("adaptive_trace_control_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive trace control.
        /// </summary>
        internal static string adaptive_trace_control_name {
            get {
                return ResourceManager.GetString("adaptive_trace_control_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add marker, {0}.
        /// </summary>
        internal static string add_marker {
            get {
                return ResourceManager.GetString("add_marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add text marker at {0}/{1:F1} dBm.
        /// </summary>
        internal static string add_marker_at {
            get {
                return ResourceManager.GetString("add_marker_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add marker to trace maximum....
        /// </summary>
        internal static string add_marker_max {
            get {
                return ResourceManager.GetString("add_marker_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add marker to maximum of trace &quot;{0}&quot;....
        /// </summary>
        internal static string add_marker_max_format {
            get {
                return ResourceManager.GetString("add_marker_max_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add signal at {0}/{1:F1} dBm.
        /// </summary>
        internal static string add_signal_menu {
            get {
                return ResourceManager.GetString("add_signal_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alt.
        /// </summary>
        internal static string alt {
            get {
                return ResourceManager.GetString("alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center frequency.
        /// </summary>
        internal static string center_frequency {
            get {
                return ResourceManager.GetString("center_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to antennas switch!.
        /// </summary>
        internal static string comm_conn_err {
            get {
                return ResourceManager.GetString("comm_conn_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful!.
        /// </summary>
        internal static string comm_conn_ok {
            get {
                return ResourceManager.GetString("comm_conn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear signal hits count?.
        /// </summary>
        internal static string confirm_clear_hits {
            get {
                return ResourceManager.GetString("confirm_clear_hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clear all of the signals?.
        /// </summary>
        internal static string confirm_clear_signals {
            get {
                return ResourceManager.GetString("confirm_clear_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create traces on selected signals?.
        /// </summary>
        internal static string confirm_create_traces {
            get {
                return ResourceManager.GetString("confirm_create_traces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all markers?.
        /// </summary>
        internal static string confirm_delete_all_markers {
            get {
                return ResourceManager.GetString("confirm_delete_all_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete antenna &quot;{0}&quot;?.
        /// </summary>
        internal static string confirm_delete_antenna {
            get {
                return ResourceManager.GetString("confirm_delete_antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current markers?.
        /// </summary>
        internal static string confirm_delete_cur_markers {
            get {
                return ResourceManager.GetString("confirm_delete_cur_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current signals?.
        /// </summary>
        internal static string confirm_delete_cur_signals {
            get {
                return ResourceManager.GetString("confirm_delete_cur_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace &quot;{0}&quot; ({1}) already loaded.
        ///Delete existent trace?.
        /// </summary>
        internal static string confirm_delete_cur_trace {
            get {
                return ResourceManager.GetString("confirm_delete_cur_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete selected signals?.
        /// </summary>
        internal static string confirm_delete_marked_signals {
            get {
                return ResourceManager.GetString("confirm_delete_marked_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete selected reports?.
        /// </summary>
        internal static string confirm_delete_reports {
            get {
                return ResourceManager.GetString("confirm_delete_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete selected markers?.
        /// </summary>
        internal static string confirm_delete_selected_markers {
            get {
                return ResourceManager.GetString("confirm_delete_selected_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete trace &quot;{0}&quot; ({1}-{2}/{3})?.
        /// </summary>
        internal static string confirm_delete_trace {
            get {
                return ResourceManager.GetString("confirm_delete_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} already exists. Do you want to overwrite it?.
        /// </summary>
        internal static string confirm_file_overwrite {
            get {
                return ResourceManager.GetString("confirm_file_overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All existent traces, markers and signals will be deleted.
        ///Continue loading?.
        /// </summary>
        internal static string confirm_ks_load {
            get {
                return ResourceManager.GetString("confirm_ks_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports settings was saved!.
        /// </summary>
        internal static string confirm_save_report {
            get {
                return ResourceManager.GetString("confirm_save_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to save system configuration?.
        /// </summary>
        internal static string confirm_save_system_settings {
            get {
                return ResourceManager.GetString("confirm_save_system_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace contains masurement points which will be deleted.
        ///Do you wish to continue?.
        /// </summary>
        internal static string confirm_trace_change_params {
            get {
                return ResourceManager.GetString("confirm_trace_change_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace control reinitialized!.
        /// </summary>
        internal static string control_reset_ok {
            get {
                return ResourceManager.GetString("control_reset_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor.
        /// </summary>
        internal static string cursor_name {
            get {
                return ResourceManager.GetString("cursor_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dB.
        /// </summary>
        internal static string db {
            get {
                return ResourceManager.GetString("db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dBm.
        /// </summary>
        internal static string dbm {
            get {
                return ResourceManager.GetString("dbm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver is in use and can&apos;t be deleted!.
        /// </summary>
        internal static string err_delete_rpu {
            get {
                return ResourceManager.GetString("err_delete_rpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start frequency can not be less or equal to stop frequency!.
        /// </summary>
        internal static string err_fstart_fstop {
            get {
                return ResourceManager.GetString("err_fstart_fstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; not found!.
        /// </summary>
        internal static string err_ks_not_found {
            get {
                return ResourceManager.GetString("err_ks_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not restore trace scan settings.
        ///Scan settings was reset..
        /// </summary>
        internal static string err_loading_scan_params {
            get {
                return ResourceManager.GetString("err_loading_scan_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading KAOR state!.
        /// </summary>
        internal static string err_loading_state {
            get {
                return ResourceManager.GetString("err_loading_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading trace &quot;{0}&quot;.
        /// </summary>
        internal static string err_loading_trace {
            get {
                return ResourceManager.GetString("err_loading_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect antenna selected for Direct Antenna Manager!.
        /// </summary>
        internal static string err_manager_invalid_antenna {
            get {
                return ResourceManager.GetString("err_manager_invalid_antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of trace points can&apos;t be greater then 2000000000!.
        /// </summary>
        internal static string err_points_limit {
            get {
                return ResourceManager.GetString("err_points_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving report to &quot;{0}&quot;.
        /// </summary>
        internal static string err_save_report {
            get {
                return ResourceManager.GetString("err_save_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving report settings!.
        /// </summary>
        internal static string err_saving_report_settings {
            get {
                return ResourceManager.GetString("err_saving_report_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving system configuration to &quot;{0}&quot;.
        /// </summary>
        internal static string err_saving_settings {
            get {
                return ResourceManager.GetString("err_saving_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error turning on {0} receiver!.
        /// </summary>
        internal static string err_turning_on_rpu {
            get {
                return ResourceManager.GetString("err_turning_on_rpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting {0}!.
        /// </summary>
        internal static string error_deleting_report {
            get {
                return ResourceManager.GetString("error_deleting_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export report....
        /// </summary>
        internal static string export_report {
            get {
                return ResourceManager.GetString("export_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHz.
        /// </summary>
        internal static string ghz {
            get {
                return ResourceManager.GetString("ghz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hz.
        /// </summary>
        internal static string hz {
            get {
                return ResourceManager.GetString("hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report saved to &quot;{0}&quot;.
        /// </summary>
        internal static string inf_report_saved {
            get {
                return ResourceManager.GetString("inf_report_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System configuration is saved to &quot;{0}&quot;
        ///Previous system configuration is saved to &quot;{1}&quot;.
        /// </summary>
        internal static string inf_settings_saved {
            get {
                return ResourceManager.GetString("inf_settings_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid altude specified!.
        /// </summary>
        internal static string invalid_altitude {
            get {
                return ResourceManager.GetString("invalid_altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid direction specified!.
        /// </summary>
        internal static string invalid_direction {
            get {
                return ResourceManager.GetString("invalid_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid direction diagram width specified!.
        /// </summary>
        internal static string invalid_dnwidth {
            get {
                return ResourceManager.GetString("invalid_dnwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid latitude specified!.
        /// </summary>
        internal static string invalid_latitude {
            get {
                return ResourceManager.GetString("invalid_latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid longitude specified!.
        /// </summary>
        internal static string invalid_longitude {
            get {
                return ResourceManager.GetString("invalid_longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kHz.
        /// </summary>
        internal static string khz {
            get {
                return ResourceManager.GetString("khz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markers set (*.kma) | *.kma.
        /// </summary>
        internal static string kma_filter {
            get {
                return ResourceManager.GetString("kma_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System state (*.ks) | *.ks.
        /// </summary>
        internal static string ks_filter {
            get {
                return ResourceManager.GetString("ks_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals set (*.ksi) | *.ksi.
        /// </summary>
        internal static string ksi_filter {
            get {
                return ResourceManager.GetString("ksi_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAOR traces (*.ktr) | *.ktr.
        /// </summary>
        internal static string ktr_filter {
            get {
                return ResourceManager.GetString("ktr_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lat.
        /// </summary>
        internal static string lat {
            get {
                return ResourceManager.GetString("lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t be greater than {0} Hz..
        /// </summary>
        internal static string limit_max_freq {
            get {
                return ResourceManager.GetString("limit_max_freq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t be less than {0} Hz..
        /// </summary>
        internal static string limit_min_freq {
            get {
                return ResourceManager.GetString("limit_min_freq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load markers set....
        /// </summary>
        internal static string load_markers {
            get {
                return ResourceManager.GetString("load_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select RCS state file to load....
        /// </summary>
        internal static string load_rcs_state {
            get {
                return ResourceManager.GetString("load_rcs_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load signals set....
        /// </summary>
        internal static string load_signals {
            get {
                return ResourceManager.GetString("load_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lon.
        /// </summary>
        internal static string lon {
            get {
                return ResourceManager.GetString("lon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker.
        /// </summary>
        internal static string marker {
            get {
                return ResourceManager.GetString("marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of measures.
        /// </summary>
        internal static string measures_count {
            get {
                return ResourceManager.GetString("measures_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MHz.
        /// </summary>
        internal static string mhz {
            get {
                return ResourceManager.GetString("mhz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        internal static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New trace.
        /// </summary>
        internal static string new_trace {
            get {
                return ResourceManager.GetString("new_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default signal selected!.
        /// </summary>
        internal static string no_default_signal {
            get {
                return ResourceManager.GetString("no_default_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recevier.
        /// </summary>
        internal static string no_rpu {
            get {
                return ResourceManager.GetString("no_rpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no receiver selected!.
        /// </summary>
        internal static string no_rpus_present {
            get {
                return ResourceManager.GetString("no_rpus_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no scan settings for trace &quot;{0}&quot;
        ///Do you want to setup scan now?.
        /// </summary>
        internal static string no_scan_params {
            get {
                return ResourceManager.GetString("no_scan_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no scan or control traces.
        /// </summary>
        internal static string no_scan_traces {
            get {
                return ResourceManager.GetString("no_scan_traces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no selected signals.
        /// </summary>
        internal static string no_selected_signals {
            get {
                return ResourceManager.GetString("no_selected_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open trace....
        /// </summary>
        internal static string open_trace {
            get {
                return ResourceManager.GetString("open_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAOR report (*.pdf) | *.pdf.
        /// </summary>
        internal static string pdf_filter {
            get {
                return ResourceManager.GetString("pdf_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power, dBm.
        /// </summary>
        internal static string power {
            get {
                return ResourceManager.GetString("power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power allocation.
        /// </summary>
        internal static string power_allocation {
            get {
                return ResourceManager.GetString("power_allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range signal.
        /// </summary>
        internal static string range_signal {
            get {
                return ResourceManager.GetString("range_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Control System.
        /// </summary>
        internal static string rcs_descr {
            get {
                return ResourceManager.GetString("rcs_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Control System.
        /// </summary>
        internal static string rcs_name {
            get {
                return ResourceManager.GetString("rcs_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Among them:.
        /// </summary>
        internal static string report_among_them {
            get {
                return ResourceManager.GetString("report_among_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenna / Receiver.
        /// </summary>
        internal static string report_AntRpu {
            get {
                return ResourceManager.GetString("report_AntRpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band.
        /// </summary>
        internal static string report_band {
            get {
                return ResourceManager.GetString("report_band", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string report_control {
            get {
                return ResourceManager.GetString("report_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous.
        /// </summary>
        internal static string report_danger {
            get {
                return ResourceManager.GetString("report_danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string report_description {
            get {
                return ResourceManager.GetString("report_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string report_frequency {
            get {
                return ResourceManager.GetString("report_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits.
        /// </summary>
        internal static string report_hit_count {
            get {
                return ResourceManager.GetString("report_hit_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string report_name {
            get {
                return ResourceManager.GetString("report_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signals selected.
        /// </summary>
        internal static string report_no_signals_selected {
            get {
                return ResourceManager.GetString("report_no_signals_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string report_notes {
            get {
                return ResourceManager.GetString("report_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible person:.
        /// </summary>
        internal static string report_person {
            get {
                return ResourceManager.GetString("report_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.
        /// </summary>
        internal static string report_safe {
            get {
                return ResourceManager.GetString("report_safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal &apos;{0}&apos; report ({1}).
        /// </summary>
        internal static string report_signal {
            get {
                return ResourceManager.GetString("report_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base frequency: {0} / Signal band: {1} / Signal description: {2} / Hit count: {3}.
        /// </summary>
        internal static string report_signal_header {
            get {
                return ResourceManager.GetString("report_signal_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals report.
        /// </summary>
        internal static string report_signals {
            get {
                return ResourceManager.GetString("report_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals summary table.
        /// </summary>
        internal static string report_signals_table {
            get {
                return ResourceManager.GetString("report_signals_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string report_signals_table2 {
            get {
                return ResourceManager.GetString("report_signals_table2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspicious.
        /// </summary>
        internal static string report_suspic {
            get {
                return ResourceManager.GetString("report_suspic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test record.
        /// </summary>
        internal static string report_test_record {
            get {
                return ResourceManager.GetString("report_test_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test report.
        /// </summary>
        internal static string report_test_report {
            get {
                return ResourceManager.GetString("report_test_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string report_time {
            get {
                return ResourceManager.GetString("report_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string report_total {
            get {
                return ResourceManager.GetString("report_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total hits: {0}.
        /// </summary>
        internal static string report_total_hits {
            get {
                return ResourceManager.GetString("report_total_hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string report_unknown {
            get {
                return ResourceManager.GetString("report_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create trace with this receiver type!.
        /// </summary>
        internal static string rpu_cant_create_trace {
            get {
                return ResourceManager.GetString("rpu_cant_create_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t scan with this receiver type!.
        /// </summary>
        internal static string rpu_cant_scan {
            get {
                return ResourceManager.GetString("rpu_cant_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save markers set....
        /// </summary>
        internal static string save_markers {
            get {
                return ResourceManager.GetString("save_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select RCS state file to save into....
        /// </summary>
        internal static string save_rcs_state {
            get {
                return ResourceManager.GetString("save_rcs_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save signals set....
        /// </summary>
        internal static string save_signals {
            get {
                return ResourceManager.GetString("save_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save trace....
        /// </summary>
        internal static string save_trace {
            get {
                return ResourceManager.GetString("save_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected markers:.
        /// </summary>
        internal static string selected_markers {
            get {
                return ResourceManager.GetString("selected_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal appearance was detected.
        /// </summary>
        internal static string signal_appear {
            get {
                return ResourceManager.GetString("signal_appear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal disappearance was detected.
        /// </summary>
        internal static string signal_disappear {
            get {
                return ResourceManager.GetString("signal_disappear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of signals.
        /// </summary>
        internal static string signals_list {
            get {
                return ResourceManager.GetString("signals_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single frequncy signal.
        /// </summary>
        internal static string single_freq_signal {
            get {
                return ResourceManager.GetString("single_freq_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span.
        /// </summary>
        internal static string span {
            get {
                return ResourceManager.GetString("span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start frequency.
        /// </summary>
        internal static string start_frequency {
            get {
                return ResourceManager.GetString("start_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing base system....
        /// </summary>
        internal static string status_initializing_base {
            get {
                return ResourceManager.GetString("status_initializing_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading antennas configuration....
        /// </summary>
        internal static string status_loading_antennas {
            get {
                return ResourceManager.GetString("status_loading_antennas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading system configuration....
        /// </summary>
        internal static string status_loading_configuration {
            get {
                return ResourceManager.GetString("status_loading_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading radios configuration....
        /// </summary>
        internal static string status_loading_rpu {
            get {
                return ResourceManager.GetString("status_loading_rpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0} receiver parameters....
        /// </summary>
        internal static string status_loading_rpu_params {
            get {
                return ResourceManager.GetString("status_loading_rpu_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving ОК!.
        /// </summary>
        internal static string status_save_ok {
            get {
                return ResourceManager.GetString("status_save_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving {0}.
        /// </summary>
        internal static string status_saving {
            get {
                return ResourceManager.GetString("status_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning system on....
        /// </summary>
        internal static string status_turning_on {
            get {
                return ResourceManager.GetString("status_turning_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning {0} receiver on....
        /// </summary>
        internal static string status_turning_on_rpu {
            get {
                return ResourceManager.GetString("status_turning_on_rpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop frequency.
        /// </summary>
        internal static string stop_frequency {
            get {
                return ResourceManager.GetString("stop_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenna description.
        /// </summary>
        internal static string str_antenna_descr {
            get {
                return ResourceManager.GetString("str_antenna_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New antenna.
        /// </summary>
        internal static string str_new_antenna {
            get {
                return ResourceManager.GetString("str_new_antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace control.
        /// </summary>
        internal static string trace_control {
            get {
                return ResourceManager.GetString("trace_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace &quot;{0}&quot; has no max in visible range.
        /// </summary>
        internal static string trace_no_max {
            get {
                return ResourceManager.GetString("trace_no_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset scan?.
        /// </summary>
        internal static string trace_scan_reset {
            get {
                return ResourceManager.GetString("trace_scan_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown report (*.*) | *.*.
        /// </summary>
        internal static string unk_filter {
            get {
                return ResourceManager.GetString("unk_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAOR audio record (*.wav) | *.wav.
        /// </summary>
        internal static string wav_filter {
            get {
                return ResourceManager.GetString("wav_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong frequency format!.
        /// </summary>
        internal static string wrong_frequency_format {
            get {
                return ResourceManager.GetString("wrong_frequency_format", resourceCulture);
            }
        }
    }
}
