//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPUICOMR8500.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPUICOMR8500.I18N.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to receiver!.
        /// </summary>
        internal static string connection_error {
            get {
                return ResourceManager.GetString("connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull connection!.
        /// </summary>
        internal static string connection_ok {
            get {
                return ResourceManager.GetString("connection_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty memory!.
        /// </summary>
        internal static string empty_mem {
            get {
                return ResourceManager.GetString("empty_mem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have select invalid antenna!.
        /// </summary>
        internal static string err_invalid_antenna {
            get {
                return ResourceManager.GetString("err_invalid_antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid antennas manager is selected!.
        /// </summary>
        internal static string err_invalid_manager {
            get {
                return ResourceManager.GetString("err_invalid_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected port is already in use!.
        /// </summary>
        internal static string err_port_open {
            get {
                return ResourceManager.GetString("err_port_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICOM R-8500 Receiver (100кГц - 2ГГц).
        /// </summary>
        internal static string icom_descr {
            get {
                return ResourceManager.GetString("icom_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICOM R-8500.
        /// </summary>
        internal static string icom_name {
            get {
                return ResourceManager.GetString("icom_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace is out of 100kHz - 2GHz range. Scanning will be performed only in that range..
        /// </summary>
        internal static string invalid_trace {
            get {
                return ResourceManager.GetString("invalid_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace points step is not equal to powermeter filter band.
        ///Points step: {0}
        ///Powermeter filter band: {1}
        ///Do you want to set trace points step equal to powermeter filter band?
        ///
        ///WARNING: Previous scan results will be lost!.
        /// </summary>
        internal static string warn_step_change {
            get {
                return ResourceManager.GetString("warn_step_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFM can&apos;t be set with frequencies below 30MHz.
        /// </summary>
        internal static string wfm_error {
            get {
                return ResourceManager.GetString("wfm_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFM filter band can be used only for frequencies above 30MHz.
        ///This trase has frequency range: {0} - {1}.
        /// </summary>
        internal static string wfm_error_long {
            get {
                return ResourceManager.GetString("wfm_error_long", resourceCulture);
            }
        }
    }
}
