//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.3053
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaorCore.I18N {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaorCore.I18N.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adaptive trace control with upper and lower thresholds.
        /// </summary>
        internal static string adaptive_trace_control_descr {
            get {
                return ResourceManager.GetString("adaptive_trace_control_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adaptive trace control.
        /// </summary>
        internal static string adaptive_trace_control_name {
            get {
                return ResourceManager.GetString("adaptive_trace_control_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add marker, {0}.
        /// </summary>
        internal static string add_marker {
            get {
                return ResourceManager.GetString("add_marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add text marker at {0}/{1:F1} dBm.
        /// </summary>
        internal static string add_marker_at {
            get {
                return ResourceManager.GetString("add_marker_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add marker to trace maximum....
        /// </summary>
        internal static string add_marker_max {
            get {
                return ResourceManager.GetString("add_marker_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add marker to maximum of trace &quot;{0}&quot;....
        /// </summary>
        internal static string add_marker_max_format {
            get {
                return ResourceManager.GetString("add_marker_max_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add signal at {0}/{1:F1} dBm.
        /// </summary>
        internal static string add_signal_menu {
            get {
                return ResourceManager.GetString("add_signal_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на alt.
        /// </summary>
        internal static string alt {
            get {
                return ResourceManager.GetString("alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Center frequency.
        /// </summary>
        internal static string center_frequency {
            get {
                return ResourceManager.GetString("center_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error connecting to antennas switch!.
        /// </summary>
        internal static string comm_conn_err {
            get {
                return ResourceManager.GetString("comm_conn_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection successful!.
        /// </summary>
        internal static string comm_conn_ok {
            get {
                return ResourceManager.GetString("comm_conn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear signal hits count?.
        /// </summary>
        internal static string confirm_clear_hits {
            get {
                return ResourceManager.GetString("confirm_clear_hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to clear all of the signals?.
        /// </summary>
        internal static string confirm_clear_signals {
            get {
                return ResourceManager.GetString("confirm_clear_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create traces on selected signals?.
        /// </summary>
        internal static string confirm_create_traces {
            get {
                return ResourceManager.GetString("confirm_create_traces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all markers?.
        /// </summary>
        internal static string confirm_delete_all_markers {
            get {
                return ResourceManager.GetString("confirm_delete_all_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to delete antenna &quot;{0}&quot;?.
        /// </summary>
        internal static string confirm_delete_antenna {
            get {
                return ResourceManager.GetString("confirm_delete_antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete current markers?.
        /// </summary>
        internal static string confirm_delete_cur_markers {
            get {
                return ResourceManager.GetString("confirm_delete_cur_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete current signals?.
        /// </summary>
        internal static string confirm_delete_cur_signals {
            get {
                return ResourceManager.GetString("confirm_delete_cur_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trace &quot;{0}&quot; ({1}) already loaded.
        ///Delete existent trace?.
        /// </summary>
        internal static string confirm_delete_cur_trace {
            get {
                return ResourceManager.GetString("confirm_delete_cur_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to delete selected signals?.
        /// </summary>
        internal static string confirm_delete_marked_signals {
            get {
                return ResourceManager.GetString("confirm_delete_marked_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to delete selected reports?.
        /// </summary>
        internal static string confirm_delete_reports {
            get {
                return ResourceManager.GetString("confirm_delete_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to delete selected markers?.
        /// </summary>
        internal static string confirm_delete_selected_markers {
            get {
                return ResourceManager.GetString("confirm_delete_selected_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to delete trace &quot;{0}&quot; ({1}-{2}/{3})?.
        /// </summary>
        internal static string confirm_delete_trace {
            get {
                return ResourceManager.GetString("confirm_delete_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File {0} already exists. Do you want to overwrite it?.
        /// </summary>
        internal static string confirm_file_overwrite {
            get {
                return ResourceManager.GetString("confirm_file_overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All existent traces, markers and signals will be deleted.
        ///Continue loading?.
        /// </summary>
        internal static string confirm_ks_load {
            get {
                return ResourceManager.GetString("confirm_ks_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reports settings was saved!.
        /// </summary>
        internal static string confirm_save_report {
            get {
                return ResourceManager.GetString("confirm_save_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to save system configuration?.
        /// </summary>
        internal static string confirm_save_system_settings {
            get {
                return ResourceManager.GetString("confirm_save_system_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trace contains masurement points which will be deleted.
        ///Do you wish to continue?.
        /// </summary>
        internal static string confirm_trace_change_params {
            get {
                return ResourceManager.GetString("confirm_trace_change_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        internal static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trace control reinitialized!.
        /// </summary>
        internal static string control_reset_ok {
            get {
                return ResourceManager.GetString("control_reset_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cursor.
        /// </summary>
        internal static string cursor_name {
            get {
                return ResourceManager.GetString("cursor_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dB.
        /// </summary>
        internal static string db {
            get {
                return ResourceManager.GetString("db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dBm.
        /// </summary>
        internal static string dbm {
            get {
                return ResourceManager.GetString("dbm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receiver is in use and can&apos;t be deleted!.
        /// </summary>
        internal static string err_delete_rpu {
            get {
                return ResourceManager.GetString("err_delete_rpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start frequency can not be less or equal to stop frequency!.
        /// </summary>
        internal static string err_fstart_fstop {
            get {
                return ResourceManager.GetString("err_fstart_fstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File &quot;{0}&quot; not found!.
        /// </summary>
        internal static string err_ks_not_found {
            get {
                return ResourceManager.GetString("err_ks_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not restore trace scan settings.
        ///Scan settings was reset..
        /// </summary>
        internal static string err_loading_scan_params {
            get {
                return ResourceManager.GetString("err_loading_scan_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error loading KAOR state!.
        /// </summary>
        internal static string err_loading_state {
            get {
                return ResourceManager.GetString("err_loading_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error loading trace &quot;{0}&quot;.
        /// </summary>
        internal static string err_loading_trace {
            get {
                return ResourceManager.GetString("err_loading_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect antenna selected for Direct Antenna Manager!.
        /// </summary>
        internal static string err_manager_invalid_antenna {
            get {
                return ResourceManager.GetString("err_manager_invalid_antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of trace points can&apos;t be greater then 2000000000!.
        /// </summary>
        internal static string err_points_limit {
            get {
                return ResourceManager.GetString("err_points_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error saving report to &quot;{0}&quot;.
        /// </summary>
        internal static string err_save_report {
            get {
                return ResourceManager.GetString("err_save_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error saving report settings!.
        /// </summary>
        internal static string err_saving_report_settings {
            get {
                return ResourceManager.GetString("err_saving_report_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error saving system configuration to &quot;{0}&quot;.
        /// </summary>
        internal static string err_saving_settings {
            get {
                return ResourceManager.GetString("err_saving_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error turning on {0} receiver!.
        /// </summary>
        internal static string err_turning_on_rpu {
            get {
                return ResourceManager.GetString("err_turning_on_rpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error deleting {0}!.
        /// </summary>
        internal static string error_deleting_report {
            get {
                return ResourceManager.GetString("error_deleting_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export report....
        /// </summary>
        internal static string export_report {
            get {
                return ResourceManager.GetString("export_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frequency.
        /// </summary>
        internal static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GHz.
        /// </summary>
        internal static string ghz {
            get {
                return ResourceManager.GetString("ghz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hz.
        /// </summary>
        internal static string hz {
            get {
                return ResourceManager.GetString("hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report saved to &quot;{0}&quot;.
        /// </summary>
        internal static string inf_report_saved {
            get {
                return ResourceManager.GetString("inf_report_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System configuration is saved to &quot;{0}&quot;
        ///Previous system configuration is saved to &quot;{1}&quot;.
        /// </summary>
        internal static string inf_settings_saved {
            get {
                return ResourceManager.GetString("inf_settings_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid altude specified!.
        /// </summary>
        internal static string invalid_altitude {
            get {
                return ResourceManager.GetString("invalid_altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid direction specified!.
        /// </summary>
        internal static string invalid_direction {
            get {
                return ResourceManager.GetString("invalid_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid direction diagram width specified!.
        /// </summary>
        internal static string invalid_dnwidth {
            get {
                return ResourceManager.GetString("invalid_dnwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid latitude specified!.
        /// </summary>
        internal static string invalid_latitude {
            get {
                return ResourceManager.GetString("invalid_latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid longitude specified!.
        /// </summary>
        internal static string invalid_longitude {
            get {
                return ResourceManager.GetString("invalid_longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на kHz.
        /// </summary>
        internal static string khz {
            get {
                return ResourceManager.GetString("khz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Markers set (*.kma) | *.kma.
        /// </summary>
        internal static string kma_filter {
            get {
                return ResourceManager.GetString("kma_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System state (*.ks) | *.ks.
        /// </summary>
        internal static string ks_filter {
            get {
                return ResourceManager.GetString("ks_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Signals set (*.ksi)|*.ksi|&quot;Berezina&quot; report (*.rfr)|*.rfr.
        /// </summary>
        internal static string ksi_filter {
            get {
                return ResourceManager.GetString("ksi_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KAOR traces (*.ktr)|*.ktr|&quot;Berezina&quot; traces (*.tfr)|*.tfr.
        /// </summary>
        internal static string ktr_filter {
            get {
                return ResourceManager.GetString("ktr_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lat.
        /// </summary>
        internal static string lat {
            get {
                return ResourceManager.GetString("lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value can&apos;t be greater than {0} Hz..
        /// </summary>
        internal static string limit_max_freq {
            get {
                return ResourceManager.GetString("limit_max_freq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value can&apos;t be less than {0} Hz..
        /// </summary>
        internal static string limit_min_freq {
            get {
                return ResourceManager.GetString("limit_min_freq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load markers set....
        /// </summary>
        internal static string load_markers {
            get {
                return ResourceManager.GetString("load_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select RCS state file to load....
        /// </summary>
        internal static string load_rcs_state {
            get {
                return ResourceManager.GetString("load_rcs_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load signals set....
        /// </summary>
        internal static string load_signals {
            get {
                return ResourceManager.GetString("load_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lon.
        /// </summary>
        internal static string lon {
            get {
                return ResourceManager.GetString("lon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Marker.
        /// </summary>
        internal static string marker {
            get {
                return ResourceManager.GetString("marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of measures.
        /// </summary>
        internal static string measures_count {
            get {
                return ResourceManager.GetString("measures_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MHz.
        /// </summary>
        internal static string mhz {
            get {
                return ResourceManager.GetString("mhz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ms.
        /// </summary>
        internal static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New trace.
        /// </summary>
        internal static string new_trace {
            get {
                return ResourceManager.GetString("new_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No default signal selected!.
        /// </summary>
        internal static string no_default_signal {
            get {
                return ResourceManager.GetString("no_default_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No recevier.
        /// </summary>
        internal static string no_rpu {
            get {
                return ResourceManager.GetString("no_rpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no receiver selected!.
        /// </summary>
        internal static string no_rpus_present {
            get {
                return ResourceManager.GetString("no_rpus_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no scan settings for trace &quot;{0}&quot;
        ///Do you want to setup scan now?.
        /// </summary>
        internal static string no_scan_params {
            get {
                return ResourceManager.GetString("no_scan_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no scan or control traces.
        /// </summary>
        internal static string no_scan_traces {
            get {
                return ResourceManager.GetString("no_scan_traces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no selected signals.
        /// </summary>
        internal static string no_selected_signals {
            get {
                return ResourceManager.GetString("no_selected_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open trace....
        /// </summary>
        internal static string open_trace {
            get {
                return ResourceManager.GetString("open_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KAOR report (*.pdf) | *.pdf.
        /// </summary>
        internal static string pdf_filter {
            get {
                return ResourceManager.GetString("pdf_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power, dBm.
        /// </summary>
        internal static string power {
            get {
                return ResourceManager.GetString("power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power allocation.
        /// </summary>
        internal static string power_allocation {
            get {
                return ResourceManager.GetString("power_allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Question.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Range signal.
        /// </summary>
        internal static string range_signal {
            get {
                return ResourceManager.GetString("range_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Radio Control System.
        /// </summary>
        internal static string rcs_descr {
            get {
                return ResourceManager.GetString("rcs_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Radio Control System.
        /// </summary>
        internal static string rcs_name {
            get {
                return ResourceManager.GetString("rcs_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Among them:.
        /// </summary>
        internal static string report_among_them {
            get {
                return ResourceManager.GetString("report_among_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Antenna / Receiver.
        /// </summary>
        internal static string report_AntRpu {
            get {
                return ResourceManager.GetString("report_AntRpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Band.
        /// </summary>
        internal static string report_band {
            get {
                return ResourceManager.GetString("report_band", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Control.
        /// </summary>
        internal static string report_control {
            get {
                return ResourceManager.GetString("report_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dangerous.
        /// </summary>
        internal static string report_danger {
            get {
                return ResourceManager.GetString("report_danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string report_description {
            get {
                return ResourceManager.GetString("report_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frequency.
        /// </summary>
        internal static string report_frequency {
            get {
                return ResourceManager.GetString("report_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hits.
        /// </summary>
        internal static string report_hit_count {
            get {
                return ResourceManager.GetString("report_hit_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string report_name {
            get {
                return ResourceManager.GetString("report_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No signals selected.
        /// </summary>
        internal static string report_no_signals_selected {
            get {
                return ResourceManager.GetString("report_no_signals_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notes.
        /// </summary>
        internal static string report_notes {
            get {
                return ResourceManager.GetString("report_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Responsible person:.
        /// </summary>
        internal static string report_person {
            get {
                return ResourceManager.GetString("report_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Safe.
        /// </summary>
        internal static string report_safe {
            get {
                return ResourceManager.GetString("report_safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Signal &apos;{0}&apos; report ({1}).
        /// </summary>
        internal static string report_signal {
            get {
                return ResourceManager.GetString("report_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base frequency: {0} / Signal band: {1} / Signal description: {2} / Hit count: {3}.
        /// </summary>
        internal static string report_signal_header {
            get {
                return ResourceManager.GetString("report_signal_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Signals report.
        /// </summary>
        internal static string report_signals {
            get {
                return ResourceManager.GetString("report_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Signals summary table.
        /// </summary>
        internal static string report_signals_table {
            get {
                return ResourceManager.GetString("report_signals_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} {1}.
        /// </summary>
        internal static string report_signals_table2 {
            get {
                return ResourceManager.GetString("report_signals_table2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Suspicious.
        /// </summary>
        internal static string report_suspic {
            get {
                return ResourceManager.GetString("report_suspic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test record.
        /// </summary>
        internal static string report_test_record {
            get {
                return ResourceManager.GetString("report_test_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test report.
        /// </summary>
        internal static string report_test_report {
            get {
                return ResourceManager.GetString("report_test_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        internal static string report_time {
            get {
                return ResourceManager.GetString("report_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total:.
        /// </summary>
        internal static string report_total {
            get {
                return ResourceManager.GetString("report_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total hits: {0}.
        /// </summary>
        internal static string report_total_hits {
            get {
                return ResourceManager.GetString("report_total_hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undefined.
        /// </summary>
        internal static string report_unknown {
            get {
                return ResourceManager.GetString("report_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t create trace with this receiver type!.
        /// </summary>
        internal static string rpu_cant_create_trace {
            get {
                return ResourceManager.GetString("rpu_cant_create_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t scan with this receiver type!.
        /// </summary>
        internal static string rpu_cant_scan {
            get {
                return ResourceManager.GetString("rpu_cant_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save markers set....
        /// </summary>
        internal static string save_markers {
            get {
                return ResourceManager.GetString("save_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select RCS state file to save into....
        /// </summary>
        internal static string save_rcs_state {
            get {
                return ResourceManager.GetString("save_rcs_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save signals set....
        /// </summary>
        internal static string save_signals {
            get {
                return ResourceManager.GetString("save_signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save trace....
        /// </summary>
        internal static string save_trace {
            get {
                return ResourceManager.GetString("save_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected markers:.
        /// </summary>
        internal static string selected_markers {
            get {
                return ResourceManager.GetString("selected_markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Signal appearance was detected.
        /// </summary>
        internal static string signal_appear {
            get {
                return ResourceManager.GetString("signal_appear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Signal disappearance was detected.
        /// </summary>
        internal static string signal_disappear {
            get {
                return ResourceManager.GetString("signal_disappear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of signals.
        /// </summary>
        internal static string signals_list {
            get {
                return ResourceManager.GetString("signals_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Single frequncy signal.
        /// </summary>
        internal static string single_freq_signal {
            get {
                return ResourceManager.GetString("single_freq_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Span.
        /// </summary>
        internal static string span {
            get {
                return ResourceManager.GetString("span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start frequency.
        /// </summary>
        internal static string start_frequency {
            get {
                return ResourceManager.GetString("start_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initializing base system....
        /// </summary>
        internal static string status_initializing_base {
            get {
                return ResourceManager.GetString("status_initializing_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading antennas configuration....
        /// </summary>
        internal static string status_loading_antennas {
            get {
                return ResourceManager.GetString("status_loading_antennas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading system configuration....
        /// </summary>
        internal static string status_loading_configuration {
            get {
                return ResourceManager.GetString("status_loading_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading radios configuration....
        /// </summary>
        internal static string status_loading_rpu {
            get {
                return ResourceManager.GetString("status_loading_rpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading {0} receiver parameters....
        /// </summary>
        internal static string status_loading_rpu_params {
            get {
                return ResourceManager.GetString("status_loading_rpu_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving ОК!.
        /// </summary>
        internal static string status_save_ok {
            get {
                return ResourceManager.GetString("status_save_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving {0}.
        /// </summary>
        internal static string status_saving {
            get {
                return ResourceManager.GetString("status_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turning system on....
        /// </summary>
        internal static string status_turning_on {
            get {
                return ResourceManager.GetString("status_turning_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turning {0} receiver on....
        /// </summary>
        internal static string status_turning_on_rpu {
            get {
                return ResourceManager.GetString("status_turning_on_rpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop frequency.
        /// </summary>
        internal static string stop_frequency {
            get {
                return ResourceManager.GetString("stop_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Antenna description.
        /// </summary>
        internal static string str_antenna_descr {
            get {
                return ResourceManager.GetString("str_antenna_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New antenna.
        /// </summary>
        internal static string str_new_antenna {
            get {
                return ResourceManager.GetString("str_new_antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today.
        /// </summary>
        internal static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trace control.
        /// </summary>
        internal static string trace_control {
            get {
                return ResourceManager.GetString("trace_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trace &quot;{0}&quot; has no max in visible range.
        /// </summary>
        internal static string trace_no_max {
            get {
                return ResourceManager.GetString("trace_no_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to reset scan?.
        /// </summary>
        internal static string trace_scan_reset {
            get {
                return ResourceManager.GetString("trace_scan_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown report (*.*) | *.*.
        /// </summary>
        internal static string unk_filter {
            get {
                return ResourceManager.GetString("unk_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KAOR audio record (*.wav) | *.wav.
        /// </summary>
        internal static string wav_filter {
            get {
                return ResourceManager.GetString("wav_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong frequency format!.
        /// </summary>
        internal static string wrong_frequency_format {
            get {
                return ResourceManager.GetString("wrong_frequency_format", resourceCulture);
            }
        }
    }
}
